name: d8-project
recipe: drupal8

config:
  php: '7.1'
  via: nginx
  webroot: web
  drush: stable
  drupal: true
  xdebug: true
  database: mariadb

proxy:
  mailhog:
    - mail.lemp.lndo.site

services:
  database:
    portforward: 3307
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: 1026

events:
  post-start:
  - appserver: cd $LANDO_MOUNT && composer install
  - appserver: cd $LANDO_MOUNT && composer update
  - appserver: cd $LANDO_MOUNT && composer dump-autoload -o

# # # 
# drush si --db-url=mysql://drupal8:drupal8@database:3306/drupal8 --account-pass=12345
# ln -sfv ../../drupal/modules web/modules/custom
# ln -sfv ../../drupal/themes web/themes/custom
# ln -sfv ../../../drupal/config web/sites/config/sync