version: '3.1'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    port: 
      - 3307:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  