<?php

/**
 * @file
 * Contains account_form.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function account_form_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the account_form module.
    case 'help.page.account_form':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Loyalty Program Account Form') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function account_form_theme() {
  return [
    'account_form' => [
      'render element' => 'children',
    ],
  ];
}
